### ISSUE TITLE
Fehler beim Datenschutz-Cronjob

### ISSUE THREAD

**Issue by abkoch** [Wunderbyte-GmbH/moodle-mod_booking#221]
Liebes Wunderbyte-Team,

der Task zur Bearbeitung von Datenanfragen von Nutzern liefert unter Moodle 4.0.5 (20221114) mit mod_booking v7.2.7 (2022080900) folgenden Fehler:

```
Beim Aufruf von mod_booking\privacy\provider::get_contexts_for_userid ist ein Fehler aufgetreten.
Das Plugin mod_booking konnte die Verarbeitung der Daten nicht beenden. Folgende Informationen könnten den Entwickler/innen helfen:

Fehler beim Lesen der Datenbank

#0 /var/www/moodle/lib/dml/moodle_read_slave_trait.php(291): moodle_database->query_end(false)
#1 /var/www/moodle/lib/dml/mysqli_native_moodle_database.php(1212): mysqli_native_moodle_database->query_end(false)
#2 /var/www/moodle/privacy/classes/local/request/contextlist.php(71): mysqli_native_moodle_database->get_recordset_sql('\n              ...', Array)
#3 /var/www/moodle/mod/booking/classes/privacy/provider.php(158): core_privacy\local\request\contextlist->add_from_sql('(SELECT DISTINC...', Array)
#4 /var/www/moodle/lib/moodlelib.php(8127): mod_booking\privacy\provider::get_contexts_for_userid(<id>)
#5 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback('mod_booking\\pri...', 'get_contexts_fo...', Array)
#6 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_booking', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /var/www/moodle/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback('mod_booking', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#8 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(94): core_privacy\manager->get_contexts_for_userid(<id>)
#9 /var/www/moodle/lib/cronlib.php(341): tool_dataprivacy\task\process_data_request_task->execute()
#10 /var/www/moodle/lib/cronlib.php(198): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#11 /var/www/moodle/lib/cronlib.php(76): cron_run_adhoc_tasks(1671115058)
#12 /var/www/moodle/admin/cli/cron.php(178): cron_run()
#13 {main}

```
Ist der Fehler bekannt und eventuell bereits in einer neueren Version behoben?

Viele Grüße
Andreas Koch

**Comment by bernhard-wunderbyte** [comment]
Wir konnten den Fehler weder mit Booking 7.2.7 noch mit der neueren Version 7.8.3 nachstellen. Am besten, Sie updaten Booking auf **7.8.3** (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_400_DEV.zip) und probieren es dann noch einmal.

**Comment by jheenan** [comment]
Hi We have just had the issue with moodle 3.11.8
mod_booking v7.0.22.02  2021112902
we will try upgrading to v7.0.22.15 (2021112915)
